---
- name: 'Start from scratch and DELETE EVERYTHING'
  hosts: 'localhost'
  gather_facts: 'no'
  become: 'false'
 
  tasks:

    - name: 'Delete all the files'
      file:
        path: "{{ item }}"
        state: 'absent'
      loop:
        - '../cluster.yml'
        - '../cluster.rkestate'
        - '../kube_config_cluster.yml'
        - '../ssh_key_rke'
        - '../ssh_key_rke.pub'
